
package org.stockbroker.ntu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockBrokerImplService", targetNamespace = "http://ntu.stockbroker.org/", wsdlLocation = "http://localhost:8080/stockbroker?wsdl")
public class StockBrokerImplService
    extends Service
{

    private final static URL STOCKBROKERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STOCKBROKERIMPLSERVICE_EXCEPTION;
    private final static QName STOCKBROKERIMPLSERVICE_QNAME = new QName("http://ntu.stockbroker.org/", "StockBrokerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/stockbroker?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKBROKERIMPLSERVICE_WSDL_LOCATION = url;
        STOCKBROKERIMPLSERVICE_EXCEPTION = e;
    }

    public StockBrokerImplService() {
        super(__getWsdlLocation(), STOCKBROKERIMPLSERVICE_QNAME);
    }

    public StockBrokerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKBROKERIMPLSERVICE_QNAME, features);
    }

    public StockBrokerImplService(URL wsdlLocation) {
        super(wsdlLocation, STOCKBROKERIMPLSERVICE_QNAME);
    }

    public StockBrokerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKBROKERIMPLSERVICE_QNAME, features);
    }

    public StockBrokerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockBrokerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockBroker
     */
    @WebEndpoint(name = "StockBrokerImplPort")
    public StockBroker getStockBrokerImplPort() {
        return super.getPort(new QName("http://ntu.stockbroker.org/", "StockBrokerImplPort"), StockBroker.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockBroker
     */
    @WebEndpoint(name = "StockBrokerImplPort")
    public StockBroker getStockBrokerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ntu.stockbroker.org/", "StockBrokerImplPort"), StockBroker.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKBROKERIMPLSERVICE_EXCEPTION!= null) {
            throw STOCKBROKERIMPLSERVICE_EXCEPTION;
        }
        return STOCKBROKERIMPLSERVICE_WSDL_LOCATION;
    }

}
