
package org.stockbroker.ntu;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import companystock.CompanyStock;
import companystock.CompanyStockHistory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockBroker", targetNamespace = "http://ntu.stockbroker.org/")
@XmlSeeAlso({
    companystock.ObjectFactory.class,
    org.stockbroker.ntu.ObjectFactory.class
})
public interface StockBroker {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "HTTPGet")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HTTPGet", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.HTTPGet")
    @ResponseWrapper(localName = "HTTPGetResponse", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.HTTPGetResponse")
    @Action(input = "http://ntu.stockbroker.org/StockBroker/HTTPGetRequest", output = "http://ntu.stockbroker.org/StockBroker/HTTPGetResponse")
    public List<String> httpGet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns companystock.CompanyStock
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchCompanyStockDetails", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.FetchCompanyStockDetails")
    @ResponseWrapper(localName = "fetchCompanyStockDetailsResponse", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.FetchCompanyStockDetailsResponse")
    @Action(input = "http://ntu.stockbroker.org/StockBroker/fetchCompanyStockDetailsRequest", output = "http://ntu.stockbroker.org/StockBroker/fetchCompanyStockDetailsResponse")
    public CompanyStock fetchCompanyStockDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns companystock.CompanyStockHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchCompanyStockHistory", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.FetchCompanyStockHistory")
    @ResponseWrapper(localName = "fetchCompanyStockHistoryResponse", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.FetchCompanyStockHistoryResponse")
    @Action(input = "http://ntu.stockbroker.org/StockBroker/fetchCompanyStockHistoryRequest", output = "http://ntu.stockbroker.org/StockBroker/fetchCompanyStockHistoryResponse")
    public CompanyStockHistory fetchCompanyStockHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewCompanyStockDetails", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.AddNewCompanyStockDetails")
    @ResponseWrapper(localName = "addNewCompanyStockDetailsResponse", targetNamespace = "http://ntu.stockbroker.org/", className = "org.stockbroker.ntu.AddNewCompanyStockDetailsResponse")
    @Action(input = "http://ntu.stockbroker.org/StockBroker/addNewCompanyStockDetailsRequest", output = "http://ntu.stockbroker.org/StockBroker/addNewCompanyStockDetailsResponse")
    public boolean addNewCompanyStockDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        CompanyStock arg0);

}
